schema:
  - name: server
    path: /app
    commands:
      build:
        status: true
        method: go build
        args:
          - -o bin/file-metadata-api-server
          - -mod=vendor
          - main.go
      run:
        status: true
        method: bin/file-metadata-api-server
    args:
      - serve
    watcher:
      paths:
        - /
      ignore_paths:
        - bin
        - vendor
      extensions:
        - go
#      scripts:
#        - type: before
#          command: go mod tidy
