schema:
  - name: file-metadata-api-server
    path: /app
    commands:
      build:
        status: true
        method: go build
        args:
          - -o bin/file-metadata-api-server
          - -mod=vendor
          - cmd/main.go
      run:
        status: true
        method: bin/file-metadata-api-server
    watcher:
      paths:
        - /
      ignore_paths:
        - bin
        - vendor
      extensions:
        - go
      scripts:
        - type: before
          command: go mod tidy
