version: "3.8"
services:
  api:
    build: .
    env_file: .env
    volumes:
      - $PWD/pkg:/app/pkg
      - $PWD/cmd:/app/cmd
      - $PWD/go.mod:/app/go.mod
    depends_on: 
      - database
    ports:
      - "8088:80"
    networks:
      - file-metadata-api
    command: ["realize", "start"]

  database:
    image: postgres:13-alpine
    env_file: .env
    logging:
      driver: none
    volumes: 
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - file-metadata-api

  minio:
    image: minio/minio:RELEASE.2021-09-18T18-09-59Z
    logging: 
      driver: none
    volumes: 
      - minio-data:/data
    ports: 
      - 9000:9000
      - 9001:9001
    networks:
      - file-metadata-api
    command: ["server", "/data", "--console-address", ":9001"]

networks:
  file-metadata-api:

volumes: 
  pgdata:
  minio-data:
