version: "3.8"
services:
  api:
    build: .
    env_file: .test.env
    volumes:
      - $PWD/pkg:/app/pkg
      - $PWD/cmd:/app/cmd
      - $PWD/go.mod:/app/go.mod
    depends_on: 
      - database
      - minio
    ports:
      - "${PORT}:${PORT}"
    networks:
      - file-metadata-api
    command: ["realize", "start"]

  database:
    build:
      context: database
    env_file: .test.env
    ports:
      - "5433:${DB_PORT}"
    networks:
      - file-metadata-api

  minio:
    image: minio/minio
    env_file: .test.env
    logging: 
      driver: none
    volumes:
      - minio-data:/data
    ports: 
      - 9000:9000
      - 9001:9001
    networks:
      - file-metadata-api
    command: ["minio", "server", "/data", "--console-address", ":9001"]

networks:
  file-metadata-api:

volumes:
  minio-data:
